cache: apt
dist: trusty
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/virtualenv
python:
  - "3.6"
install:
  - pip install ucca
env:
  matrix:
  - DATASET=xml
  - DATASET=pickle
script:
  - python -m scripts.validate $DATASET || echo Ignoring validation failures

