cache: apt
dist: trusty
sudo: false
language: python
cache:
  pip: true
  directories:
  - $HOME/virtualenv
python:
  - "3.6"
install:
  - pip install ucca
env:
  matrix:
  - DATASET=wiki/xml
  - DATASET=wiki/pickle
  - DATASET=vmlslm/en
  - DATASET=vmlslm/fr
  - DATASET=20k_de/xml
script:
  - python -m scripts.validate $DATASET || echo Ignoring validation failures

